name: Build SmartDNS IPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc make pkg-config

    - name: Prepare output directory
      run: mkdir -p ./package/output

    - name: Build smartdns openwrt package
      working-directory: ./package
      run: |
        chmod +x build-pkg.sh
        ./build-pkg.sh --platform openwrt --arch aarch64_cortex-a53 --outputdir ./output

    - name: List built packages
      run: ls -l ./package/output

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: smartdns-ipk
        path: ./package/output/*.ipk
